df <- read.table(file="household_power_consumption.txt",sep=";",header=TRUE, skip = grep("1/2/2007", readLines("household_power_consumption.txt")) - 1, nrows = 2879) 
colnames(df)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
x<-as.POSIXct(paste(df$Date, df$Time), format="%d/%m/%Y %H:%M:%S")
png(filename = "Plot3.png", width=480, height=480)
plot(x,df$Sub_metering_1,type="n",ylab="Energy sub metering")
points(x,df$Sub_metering_1,col="black","l")
points(x,df$Sub_metering_2,col="red","l")
points(x,df$Sub_metering_3,col="blue","l")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1))
dev.off()